name: 07 - Using expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: input value description
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu_latest
    steps:
      - name: "[debug] Print start-up"
        if: ${{inputs.debug}}
        run: |
          echo "Trigger by: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "OS: ${{runner.os}}"
      - name: "[debug]: Print when trigger from main branch"
        if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
        run: |
          echo "I was on main branch"
