name: 09 - functions
on:
  push:
  workflow_dispatch:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failling step
        run: exit 1
      - name: I will be skipped
        if: ${{success()}}
        run: echo "I will be printed if previous step was success"
      - name: I will executed
        if: ${{ failure()}}
        run: echo "I will be executed if any previos step failed"
      - name: I will executed
        if: ${{!cancelled()}}
        run: echo "I will always print , except when the workflow is cancelled"
      - name: I will executed when cancelled
        if: ${{cancelled()}}
        run: echo "I will only print if the workflow is cancelled"
